version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

python:
  install:
    - requirements: ./requirements.txt

sphinx:
  builder: html
  configuration: doc/conf.py
  fail_on_warning: false

formats: all
